### ISSUE TITLE
Exception during start up

### ISSUE THREAD

**Issue by Joker9944** [Frityet/H3VRModInstaller#11]
Hello everyone

Just downloaded version 0.5.2 and got an exception during startup. The app runs fine but it' not possible to download anything. Attached the full log.

![image](https://user-images.githubusercontent.com/9194199/106179527-74a92780-619b-11eb-8938-2bd9cb4f70a4.png)

`System.NullReferenceException: Object reference not set to an instance of an object.
   at H3VRModInstaller.GUI.mainwindow.LoadGUI(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)`

[error.log](https://github.com/Frityet/H3VRModInstaller/files/5889199/error.log)

Edit: Added app version

**Comment by Joker9944** [comment]
Hello everyone

Turns out that I should read to end of the readme. I moved the app to the right location and everything works as expected now.

Maybe add a check and message for people who don't read like me?

Kind Regards
